Add BK configuration stuff
bk: 43da9ed9AfUSA7natMhDtg8ZqBeksw

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCLSH_PROG BUILD_TCLSH MAN_FLAGS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP TCL_THREADS RANLIB ac_ct_RANLIB AR LIBOBJS TCL_LIBS DL_LIBS DL_OBJS PLAT_OBJS PLAT_SRCS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING LDFLAGS_DEBUG LDFLAGS_OPTIMIZE CC_SEARCH_FLAGS LD_SEARCH_FLAGS STLIB_LD SHLIB_LD TCL_SHLIB_LD_EXTRAS TK_SHLIB_LD_EXTRAS SHLIB_LD_LIBS SHLIB_CFLAGS SHLIB_SUFFIX MAKE_LIB MAKE_STUB_LIB INSTALL_LIB INSTALL_STUB_LIB CFLAGS_DEFAULT LDFLAGS_DEFAULT XFT_CFLAGS XFT_LIBS UNIX_FONT_OBJS TK_VERSION TK_MAJOR_VERSION TK_MINOR_VERSION TK_PATCH_LEVEL TK_YEAR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_STUB_LIB_PATH TK_INCLUDE_SPEC TK_BUILD_STUB_LIB_SPEC TK_BUILD_STUB_LIB_PATH TK_SRC_DIR TK_SHARED_BUILD LD_LIBRARY_PATH_VAR TK_BUILD_LIB_SPEC TK_BUILD_EXP_FILE TK_EXP_FILE TCL_STUB_FLAGS XINCLUDES XLIBSW LOCALES TK_WINDOWINGSYSTEM TK_PKG_DIR TK_LIBRARY PRIVATE_INCLUDE_DIR HTML_DIR EXTRA_CC_SWITCHES EXTRA_INSTALL EXTRA_INSTALL_BINARIES EXTRA_BUILD_HTML EXTRA_WISH_LIBS TK_RSRC_FILE WISH_RSRC_FILE LIB_RSRC_FILE APP_RSRC_FILE REZ REZ_FLAGS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCLSH_PROG BUILD_TCLSH MAN_FLAGS BK_DIR BK_HDRS BK_SRCS BK_OBJS BK_INCLUDES BK_LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP TCL_THREADS RANLIB ac_ct_RANLIB AR LIBOBJS TCL_LIBS DL_LIBS DL_OBJS PLAT_OBJS PLAT_SRCS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING LDFLAGS_DEBUG LDFLAGS_OPTIMIZE CC_SEARCH_FLAGS LD_SEARCH_FLAGS STLIB_LD SHLIB_LD TCL_SHLIB_LD_EXTRAS TK_SHLIB_LD_EXTRAS SHLIB_LD_LIBS SHLIB_CFLAGS SHLIB_SUFFIX MAKE_LIB MAKE_STUB_LIB INSTALL_LIB INSTALL_STUB_LIB CFLAGS_DEFAULT LDFLAGS_DEFAULT XFT_CFLAGS XFT_LIBS UNIX_FONT_OBJS TK_VERSION TK_MAJOR_VERSION TK_MINOR_VERSION TK_PATCH_LEVEL TK_YEAR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_STUB_LIB_PATH TK_INCLUDE_SPEC TK_BUILD_STUB_LIB_SPEC TK_BUILD_STUB_LIB_PATH TK_SRC_DIR TK_SHARED_BUILD LD_LIBRARY_PATH_VAR TK_BUILD_LIB_SPEC TK_BUILD_EXP_FILE TK_EXP_FILE TCL_STUB_FLAGS XINCLUDES XLIBSW LOCALES TK_WINDOWINGSYSTEM TK_PKG_DIR TK_LIBRARY PRIVATE_INCLUDE_DIR HTML_DIR EXTRA_CC_SWITCHES EXTRA_INSTALL EXTRA_INSTALL_BINARIES EXTRA_BUILD_HTML EXTRA_WISH_LIBS TK_RSRC_FILE WISH_RSRC_FILE LIB_RSRC_FILE APP_RSRC_FILE REZ REZ_FLAGS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -871,6 +871,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-tcl              directory containing tcl configuration
                           (tclConfig.sh)
+  --with-bk              directory containing BK source
   --with-x                use the X Window System
 
 Some influential environment variables:
@@ -1637,6 +1638,77 @@ fi;
 echo "${ECHO_T}$enableval" >&6
 
 
+
+
+#------------------------------------------------------------------------
+# Try to find BitKeeper source repo
+#------------------------------------------------------------------------
+
+	if test x"${no_bk}" = x ; then
+		# reset no_bk in case something fails
+		no_bk=true
+
+# Check whether --with-bk or --without-bk was given.
+if test "${with_bk+set}" = set; then
+  withval="$with_bk"
+  with_bksource=${withval}
+fi;
+		echo "$as_me:$LINENO: checking for BK source tree" >&5
+echo $ECHO_N "checking for BK source tree... $ECHO_C" >&6
+		if test x"${with_bksource}" != x ; then
+			if test -f "${with_bksource}/tclkey.h" ; then
+				ac_cv_c_bksource=`(cd ${with_bksource}/src ; pwd)`
+			else
+				{ { echo "$as_me:$LINENO: error: ${with_bksource}/src directory does not contain tclkey.h" >&5
+echo "$as_me: error: ${with_bksource}/src directory does not contain tclkey.h" >&2;}
+   { (exit 1); exit 1; }; }
+			fi
+		fi
+
+		# Now check for it in the parent directory
+		if test x"${ac_cv_c_bksource}" = x ; then
+			if test -f "../../../../tclkey.h" ; then
+				ac_cv_c_bksource=`(cd ../../../.. ; pwd)`
+			fi
+		fi
+
+		if test x"${ac_cv_c_bksource}" = x ; then
+			BK_DIR=""
+			BK_HDRS="BK_HDRS = "
+			BK_SRCS="BK_SRCS = "
+			BK_OBJS="BK_OBJS = "
+			BK_LIBS="BK_LIBS = "
+			BK_INCLUDES=""
+
+
+
+
+
+
+			{ echo "$as_me:$LINENO: WARNING: Can't find BK source tree encryption disabled" >&5
+echo "$as_me: WARNING: Can't find BK source tree encryption disabled" >&2;}
+		else
+			no_bk=
+			BK_DIR=${ac_cv_c_bksource}
+			BK_HDRS=""
+			BK_SRCS=""
+			BK_OBJS=""
+			BK_LIBS=""
+			BK_INCLUDES="-I$BK_DIR"
+			cat >>confdefs.h <<\_ACEOF
+#define BK 1
+_ACEOF
+
+
+
+
+
+
+
+			echo "$as_me:$LINENO: result: found $BK_DIR" >&5
+echo "${ECHO_T}found $BK_DIR" >&6
+		fi
+	fi
 
 
 #------------------------------------------------------------------------
@@ -10418,6 +10490,12 @@ s,@TCL_STUB_LIB_SPEC@,$TCL_STUB_LIB_SPEC,;t t
 s,@TCLSH_PROG@,$TCLSH_PROG,;t t
 s,@BUILD_TCLSH@,$BUILD_TCLSH,;t t
 s,@MAN_FLAGS@,$MAN_FLAGS,;t t
+s,@BK_DIR@,$BK_DIR,;t t
+s,@BK_HDRS@,$BK_HDRS,;t t
+s,@BK_SRCS@,$BK_SRCS,;t t
+s,@BK_OBJS@,$BK_OBJS,;t t
+s,@BK_INCLUDES@,$BK_INCLUDES,;t t
+s,@BK_LIBS@,$BK_LIBS,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
